/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/csrf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Csrf */
        get: operations["csrf_api_v1_auth_csrf_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_api_v1_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Members */
        get: operations["list_members_api_v1_members_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/members/{membership_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Set Availability */
        patch: operations["set_availability_api_v1_members__membership_id__patch"];
        trace?: never;
    };
    "/api/v1/runs/{run_id}/evidence/{evidence_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Run Evidence */
        get: operations["run_evidence_api_v1_runs__run_id__evidence__evidence_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/previews/{preview_id}/evidence/{evidence_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Preview Evidence */
        get: operations["preview_evidence_api_v1_previews__preview_id__evidence__evidence_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agent/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Conversation */
        post: operations["create_conversation_api_v1_agent_conversations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agent/conversations/{conversation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Snapshot */
        get: operations["snapshot_api_v1_agent_conversations__conversation_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agent/conversations/{conversation_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Message */
        post: operations["message_api_v1_agent_conversations__conversation_id__messages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agent/conversations/{conversation_id}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm */
        post: operations["confirm_api_v1_agent_conversations__conversation_id__confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agent/conversations/{conversation_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel */
        post: operations["cancel_api_v1_agent_conversations__conversation_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agent/conversations/{conversation_id}/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Recover Create */
        post: operations["recover_create_api_v1_agent_conversations__conversation_id__create_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agent/conversations/{conversation_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Events */
        get: operations["events_api_v1_agent_conversations__conversation_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notification-groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Groups */
        get: operations["list_groups_api_v1_notification_groups_get"];
        put?: never;
        /** Create Group */
        post: operations["create_group_api_v1_notification_groups_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notification-groups/{group_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Group */
        get: operations["read_group_api_v1_notification_groups__group_id__get"];
        /** Replace Group */
        put: operations["replace_group_api_v1_notification_groups__group_id__put"];
        post?: never;
        /** Delete Group */
        delete: operations["delete_group_api_v1_notification_groups__group_id__delete"];
        options?: never;
        head?: never;
        /** Patch Group */
        patch: operations["patch_group_api_v1_notification_groups__group_id__patch"];
        trace?: never;
    };
    "/api/v1/email-templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Templates */
        get: operations["list_templates_api_v1_email_templates_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/email-templates/{template_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Template */
        get: operations["read_template_api_v1_email_templates__template_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/email-templates/{template_id}/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Preview Template */
        post: operations["preview_template_api_v1_email_templates__template_id__preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/email-deliveries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Deliveries */
        get: operations["list_deliveries_api_v1_email_deliveries_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/email-deliveries/{delivery_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Delivery */
        get: operations["read_delivery_api_v1_email_deliveries__delivery_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/monitors/{monitor_id}/notification-routes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Routes */
        get: operations["read_routes_api_v1_monitors__monitor_id__notification_routes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/monitors/{monitor_id}/notification-routes/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request Route Preview */
        post: operations["request_route_preview_api_v1_monitors__monitor_id__notification_routes_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/monitors/{monitor_id}/notification-routes/preview/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Route Preview Status */
        get: operations["route_preview_status_api_v1_monitors__monitor_id__notification_routes_preview__job_id__get"];
        put?: never;
        /** Finish Route Preview */
        post: operations["finish_route_preview_api_v1_monitors__monitor_id__notification_routes_preview__job_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/monitors/{monitor_id}/notification-routes/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm Route Preview */
        post: operations["confirm_route_preview_api_v1_monitors__monitor_id__notification_routes_confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/monitors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Monitors */
        get: operations["list_monitors_api_v1_monitors_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/monitors/{monitor_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Monitor */
        get: operations["read_monitor_api_v1_monitors__monitor_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/monitors/{monitor_id}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Monitor Runs */
        get: operations["list_monitor_runs_api_v1_monitors__monitor_id__runs_get"];
        put?: never;
        /** Start Manual Run */
        post: operations["start_manual_run_api_v1_monitors__monitor_id__runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Run */
        get: operations["read_run_api_v1_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/monitors/{monitor_id}/pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Pause Monitor */
        post: operations["pause_monitor_api_v1_monitors__monitor_id__pause_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/monitors/{monitor_id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resume Monitor */
        post: operations["resume_monitor_api_v1_monitors__monitor_id__resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Run */
        post: operations["cancel_run_api_v1_runs__run_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Events */
        get: operations["list_events_api_v1_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/{event_id}/acknowledge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Acknowledge Event */
        post: operations["acknowledge_event_api_v1_events__event_id__acknowledge_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Live */
        get: operations["live_api_v1_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready_api_v1_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ApprovalView */
        ApprovalView: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Revision */
            revision: number;
            /**
             * Preview Id
             * Format: uuid
             */
            preview_id: string;
            /** Agent Run Id */
            agent_run_id: string | null;
            /** Tool Call Id */
            tool_call_id: string | null;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /** Consumed At */
            consumed_at: string | null;
            /** Invalidated At */
            invalidated_at: string | null;
        };
        /** AttemptView */
        AttemptView: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Attempt Number */
            attempt_number: number;
            /**
             * Status
             * @enum {string}
             */
            status: "running" | "succeeded" | "failed" | "cancelled" | "discarded";
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Finished At */
            finished_at: string | null;
            /** Retryable */
            retryable: boolean;
            /** Error Code */
            error_code: string | null;
            /** Error Message */
            error_message: string | null;
        };
        /** AuthProfile */
        AuthProfile: {
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /**
             * Workspace Id
             * Format: uuid
             */
            workspace_id: string;
            /**
             * Role
             * @enum {string}
             */
            role: "admin" | "member";
            /** Email */
            email: string;
            /** Display Name */
            display_name: string;
        };
        /** Availability */
        Availability: {
            /** Active */
            active: boolean;
        };
        /** CSRFResponse */
        CSRFResponse: {
            /** Csrf Token */
            csrf_token: string;
            /** Expires At */
            expires_at: number;
        };
        /** CancelRequest */
        CancelRequest: {
            /**
             * Agent Run Id
             * Format: uuid
             */
            agent_run_id: string;
        };
        /** ConfirmRequest */
        ConfirmRequest: {
            /**
             * Draft Id
             * Format: uuid
             */
            draft_id: string;
            /** Revision */
            revision: number;
            /**
             * Preview Id
             * Format: uuid
             */
            preview_id: string;
            /** Idempotency Key */
            idempotency_key: string;
        };
        /** ConversationCreate */
        ConversationCreate: {
            /** Title */
            title?: string | null;
        };
        /** ConversationSnapshot */
        ConversationSnapshot: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Last Seq */
            last_seq: number;
            /** Messages */
            messages: components["schemas"]["MessageView"][];
            /** Runs */
            runs: components["schemas"]["webmonitor__schemas__conversations__RunView"][];
            /** Drafts */
            drafts: components["schemas"]["DraftView"][];
        };
        /** CreateMonitorResult */
        CreateMonitorResult: {
            /**
             * Task Id
             * Format: uuid
             */
            task_id: string;
            /**
             * Monitor Version Id
             * Format: uuid
             */
            monitor_version_id: string;
            /**
             * Status
             * @default active
             * @constant
             */
            status: "active";
            /**
             * Baseline Status
             * @default pending_first_success
             * @constant
             */
            baseline_status: "pending_first_success";
            /**
             * Next Run At
             * Format: date-time
             */
            next_run_at: string;
            /** Warnings */
            warnings?: string[];
        };
        /** CreateRequest */
        CreateRequest: {
            /**
             * Draft Id
             * Format: uuid
             */
            draft_id: string;
            /** Confirmed Revision */
            confirmed_revision: number;
            /** Idempotency Key */
            idempotency_key: string;
        };
        /** Delivery */
        Delivery: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Event Id
             * Format: uuid
             */
            event_id: string;
            /** Recipient */
            recipient: string;
            /**
             * Channel
             * @constant
             */
            channel: "email";
            /**
             * Template Id
             * Format: uuid
             */
            template_id: string;
            /** Template Version */
            template_version: number;
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
            /** Recipient Sources */
            recipient_sources: {
                [key: string]: unknown;
            }[];
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "sending" | "retrying" | "sent" | "failed" | "cancelled";
            /** Message Id */
            message_id: string;
            /** Attempt Count */
            attempt_count: number;
            /** Rendered Subject */
            rendered_subject: string | null;
            /** Rendered Html */
            rendered_html: string | null;
            /** Rendered Text */
            rendered_text: string | null;
            /** Last Attempt At */
            last_attempt_at: string | null;
            /** Sent At */
            sent_at: string | null;
            /** Failed At */
            failed_at: string | null;
            /** Cancelled At */
            cancelled_at: string | null;
            /** Smtp Response Code */
            smtp_response_code: number | null;
            /** Error Code */
            error_code: string | null;
            /** Error Message */
            error_message: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** DraftView */
        DraftView: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Status */
            status: string;
            /** Revision */
            revision: number | null;
            /** Spec */
            spec: {
                [key: string]: unknown;
            } | null;
            /** Spec Hash */
            spec_hash: string | null;
            preview: components["schemas"]["PreviewView"] | null;
            approval: components["schemas"]["ApprovalView"] | null;
            /** Task Id */
            task_id: string | null;
        };
        /** EventView */
        EventView: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Monitor Id
             * Format: uuid
             */
            monitor_id: string;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /**
             * Type
             * @enum {string}
             */
            type: "price_changed" | "list_changed" | "content_changed" | "run_failed" | "recovered";
            /**
             * Detected At
             * Format: date-time
             */
            detected_at: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Change */
            change: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /** Payload */
            payload: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /** Acknowledged At */
            acknowledged_at: string | null;
        };
        /** EvidenceView */
        EvidenceView: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "html" | "screenshot" | "response";
            /** Content Type */
            content_type: string;
            /** Size Bytes */
            size_bytes: number;
        };
        /** Group */
        Group: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Enabled */
            enabled: boolean;
            /** Deleted At */
            deleted_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Members */
            members: components["schemas"]["GroupMember"][];
        };
        /** GroupMember */
        GroupMember: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Email */
            email: string;
            /** Active */
            active: boolean;
        };
        /** GroupPatch */
        GroupPatch: {
            /** Name */
            name?: string | null;
            /** Enabled */
            enabled?: boolean | null;
            /** Members */
            members?: components["schemas"]["NotificationGroupMemberSpec"][] | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        JsonValue: unknown;
        /** LoginRequest */
        LoginRequest: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /** MessageRequest */
        MessageRequest: {
            /** Content */
            content: string;
            /**
             * Client Message Id
             * Format: uuid
             */
            client_message_id: string;
        };
        /** MessageView */
        MessageView: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Agent Run Id */
            agent_run_id: string | null;
            /** Client Message Id */
            client_message_id: string | null;
            /**
             * Role
             * @enum {string}
             */
            role: "user" | "assistant" | "system";
            /** Content */
            content: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** MonitorDetail */
        MonitorDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Url */
            url: string;
            /**
             * Status
             * @enum {string}
             */
            status: "active" | "paused" | "deleted";
            /**
             * Collection Mode
             * @enum {string}
             */
            collection_mode: "http" | "browser";
            /**
             * Next Run At
             * Format: date-time
             */
            next_run_at: string;
            /**
             * Baseline Status
             * @enum {string}
             */
            baseline_status: "pending_first_success" | "ready";
            /** Baseline Snapshot Id */
            baseline_snapshot_id: string | null;
            /**
             * Health Status
             * @enum {string}
             */
            health_status: "healthy" | "failed";
            /**
             * Created By User Id
             * Format: uuid
             */
            created_by_user_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Current Version Id */
            current_version_id: string | null;
            /** Spec */
            spec: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /** Version */
            version: number;
            baseline: components["schemas"]["SnapshotView"] | null;
        };
        /** MonitorView */
        MonitorView: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Url */
            url: string;
            /**
             * Status
             * @enum {string}
             */
            status: "active" | "paused" | "deleted";
            /**
             * Collection Mode
             * @enum {string}
             */
            collection_mode: "http" | "browser";
            /**
             * Next Run At
             * Format: date-time
             */
            next_run_at: string;
            /**
             * Baseline Status
             * @enum {string}
             */
            baseline_status: "pending_first_success" | "ready";
            /** Baseline Snapshot Id */
            baseline_snapshot_id: string | null;
            /**
             * Health Status
             * @enum {string}
             */
            health_status: "healthy" | "failed";
            /**
             * Created By User Id
             * Format: uuid
             */
            created_by_user_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Current Version Id */
            current_version_id: string | null;
        };
        /** NotificationGroupMemberSpec */
        NotificationGroupMemberSpec: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /**
             * Active
             * @default true
             */
            active: boolean;
        };
        /** NotificationGroupSpec */
        NotificationGroupSpec: {
            /** Name */
            name: string;
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            /** Members */
            members: components["schemas"]["NotificationGroupMemberSpec"][];
        };
        /** NotificationPayload */
        NotificationPayload: {
            monitor: components["schemas"]["PayloadMonitor"];
            event: components["schemas"]["PayloadEvent"];
            change: components["schemas"]["PayloadChange"];
            /** Fields */
            fields: {
                [key: string]: unknown;
            };
            /** Evidence Url */
            evidence_url: string;
        };
        /** Page[Delivery] */
        Page_Delivery_: {
            /** Items */
            items: components["schemas"]["Delivery"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** Page[EventView] */
        Page_EventView_: {
            /** Items */
            items: components["schemas"]["EventView"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** Page[Group] */
        Page_Group_: {
            /** Items */
            items: components["schemas"]["Group"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** Page[MonitorView] */
        Page_MonitorView_: {
            /** Items */
            items: components["schemas"]["MonitorView"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** Page[RunView] */
        Page_RunView_: {
            /** Items */
            items: components["schemas"]["webmonitor__schemas__monitor_api__RunView"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** Page[Template] */
        Page_Template_: {
            /** Items */
            items: components["schemas"]["Template"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** PayloadChange */
        PayloadChange: {
            /** Before */
            before: {
                [key: string]: unknown;
            } | null;
            /** After */
            after: {
                [key: string]: unknown;
            };
            /** Summary */
            summary: string;
        };
        /** PayloadEvent */
        PayloadEvent: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Type
             * @enum {string}
             */
            type: "price_changed" | "list_changed" | "content_changed" | "run_failed" | "recovered";
            /**
             * Detected At
             * Format: date-time
             */
            detected_at: string;
        };
        /** PayloadMonitor */
        PayloadMonitor: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Url */
            url: string;
        };
        /** PendingApprovalView */
        PendingApprovalView: {
            /**
             * Draft Id
             * Format: uuid
             */
            draft_id: string;
            /** Confirmed Revision */
            confirmed_revision: number;
            /** Idempotency Key */
            idempotency_key: string;
            /** Tool Call Id */
            tool_call_id: string;
            /** Preview Id */
            preview_id: string | null;
        };
        /** PreviewJobStatus */
        PreviewJobStatus: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Status */
            status: string;
            /** Error Code */
            error_code: string | null;
        };
        /** PreviewView */
        PreviewView: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Revision */
            revision: number;
            /** Spec Hash */
            spec_hash: string;
            /** Preview Hash */
            preview_hash: string;
            /** Extracted Data */
            extracted_data: {
                [key: string]: unknown;
            };
            /** Coverage */
            coverage: {
                [key: string]: unknown;
            };
            /** Evidence Refs */
            evidence_refs: {
                [key: string]: unknown;
            }[];
            /** Rule Simulation */
            rule_simulation: {
                [key: string]: unknown;
            };
            /** Rendered Emails */
            rendered_emails: {
                [key: string]: unknown;
            }[];
            /** Recipient Snapshot */
            recipient_snapshot: {
                [key: string]: unknown;
            }[];
            /** Template Snapshot */
            template_snapshot: {
                [key: string]: unknown;
            }[];
            /** Warnings */
            warnings: string[];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /** Invalidated At */
            invalidated_at: string | null;
        };
        /** RegisterRequest */
        RegisterRequest: {
            /** Display Name */
            display_name: string;
            /** Email */
            email: string;
            /** Password */
            password: string;
            /** Invitation Token */
            invitation_token: string;
        };
        /** RenderedEmail */
        RenderedEmail: {
            /** Subject */
            subject: string;
            /** Html */
            html: string;
            /** Text */
            text: string;
            /** Preview Html */
            preview_html: string;
        };
        /** RouteConfirmRequest */
        RouteConfirmRequest: {
            /**
             * Draft Id
             * Format: uuid
             */
            draft_id: string;
            /** Revision */
            revision: number;
            /**
             * Preview Id
             * Format: uuid
             */
            preview_id: string;
            /**
             * Base Version Id
             * Format: uuid
             */
            base_version_id: string;
            /** Idempotency Key */
            idempotency_key: string;
        };
        /** RoutePreview */
        RoutePreview: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Draft Id
             * Format: uuid
             */
            draft_id: string;
            /** Revision */
            revision: number;
            /** Preview Hash */
            preview_hash: string;
            /** Extracted Data */
            extracted_data: {
                [key: string]: unknown;
            };
            /** Coverage */
            coverage: {
                [key: string]: unknown;
            };
            /** Evidence Refs */
            evidence_refs: {
                [key: string]: unknown;
            }[];
            /** Rule Simulation */
            rule_simulation: {
                [key: string]: unknown;
            };
            /** Rendered Emails */
            rendered_emails: {
                [key: string]: unknown;
            }[];
            /** Recipient Snapshot */
            recipient_snapshot: {
                [key: string]: unknown;
            }[];
            /** Template Snapshot */
            template_snapshot: {
                [key: string]: unknown;
            }[];
            /** Warnings */
            warnings: string[];
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
        };
        /** RoutePreviewFinish */
        RoutePreviewFinish: {
            /**
             * Draft Id
             * Format: uuid
             */
            draft_id: string;
            /** Revision */
            revision: number;
        };
        /** RoutePreviewJob */
        RoutePreviewJob: {
            /**
             * Monitor Id
             * Format: uuid
             */
            monitor_id: string;
            /**
             * Base Version Id
             * Format: uuid
             */
            base_version_id: string;
            /**
             * Conversation Id
             * Format: uuid
             */
            conversation_id: string;
            /**
             * Draft Id
             * Format: uuid
             */
            draft_id: string;
            /** Revision */
            revision: number;
            /**
             * Collection Job Id
             * Format: uuid
             */
            collection_job_id: string;
            /** Status */
            status: string;
        };
        /** RoutePreviewRequest */
        RoutePreviewRequest: {
            /** Notification Group Ids */
            notification_group_ids: string[];
            /** Template Bindings */
            template_bindings: {
                [key: string]: components["schemas"]["TemplateBinding"];
            };
            /**
             * Base Version Id
             * Format: uuid
             */
            base_version_id: string;
            /** Draft Id */
            draft_id?: string | null;
        };
        /** RouteUpdate */
        RouteUpdate: {
            /**
             * Monitor Id
             * Format: uuid
             */
            monitor_id: string;
            /**
             * Monitor Version Id
             * Format: uuid
             */
            monitor_version_id: string;
            /** Version */
            version: number;
            /** Status */
            status: string;
            /** Baseline Snapshot Id */
            baseline_snapshot_id: string | null;
        };
        /** RouteView */
        RouteView: {
            /** Notification Group Ids */
            notification_group_ids: string[];
            /** Template Bindings */
            template_bindings: {
                [key: string]: components["schemas"]["TemplateBinding"];
            };
            /**
             * Base Version Id
             * Format: uuid
             */
            base_version_id: string;
            /**
             * Monitor Id
             * Format: uuid
             */
            monitor_id: string;
            /** Version */
            version: number;
        };
        /** RunDetail */
        RunDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Monitor Id
             * Format: uuid
             */
            monitor_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "succeeded" | "failed" | "cancelled" | "discarded";
            /**
             * Trigger
             * @enum {string}
             */
            trigger: "scheduled" | "manual";
            /** Attempt Count */
            attempt_count: number;
            /** Error Code */
            error_code: string | null;
            /** Error Message */
            error_message: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Started At */
            started_at: string | null;
            /** Finished At */
            finished_at: string | null;
            /** Diff */
            diff: {
                [key: string]: components["schemas"]["JsonValue"];
            } | null;
            /** Warnings */
            warnings: string[];
            /** Attempts */
            attempts: components["schemas"]["AttemptView"][];
            snapshot: components["schemas"]["SnapshotView"] | null;
            /** Evidence */
            evidence: components["schemas"]["EvidenceView"][];
        };
        /** RunResponse */
        RunResponse: {
            /**
             * Agent Run Id
             * Format: uuid
             */
            agent_run_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "waiting_approval" | "completed" | "failed" | "cancelled";
            /** Task Id */
            task_id?: string | null;
            result?: components["schemas"]["CreateMonitorResult"] | null;
        };
        /** SnapshotView */
        SnapshotView: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Extracted Data */
            extracted_data: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /** Coverage */
            coverage: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /** Evidence Refs */
            evidence_refs: components["schemas"]["EvidenceView"][];
            /**
             * Collected At
             * Format: date-time
             */
            collected_at: string;
            /** Final Url */
            final_url: string;
        };
        /** Template */
        Template: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Event Type
             * @enum {string}
             */
            event_type: "price_changed" | "list_changed" | "content_changed" | "run_failed" | "recovered";
            /** Version */
            version: number;
            /** Name */
            name: string;
            /** Is Default */
            is_default: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** TemplateBinding */
        TemplateBinding: {
            /**
             * Template Id
             * Format: uuid
             */
            template_id: string;
            /** Version */
            version: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** RunView */
        webmonitor__schemas__conversations__RunView: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "waiting_approval" | "completed" | "failed" | "cancelled";
            /**
             * Client Message Id
             * Format: uuid
             */
            client_message_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Finished At */
            finished_at: string | null;
            /** Error Code */
            error_code: string | null;
            /** Error Message */
            error_message: string | null;
            /** Result */
            result: {
                [key: string]: unknown;
            } | null;
            pending_approval?: components["schemas"]["PendingApprovalView"] | null;
            /** Checkpoint Error */
            checkpoint_error?: string | null;
        };
        /** RunView */
        webmonitor__schemas__monitor_api__RunView: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Monitor Id
             * Format: uuid
             */
            monitor_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "succeeded" | "failed" | "cancelled" | "discarded";
            /**
             * Trigger
             * @enum {string}
             */
            trigger: "scheduled" | "manual";
            /** Attempt Count */
            attempt_count: number;
            /** Error Code */
            error_code: string | null;
            /** Error Message */
            error_message: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Started At */
            started_at: string | null;
            /** Finished At */
            finished_at: string | null;
            /** Diff */
            diff: {
                [key: string]: components["schemas"]["JsonValue"];
            } | null;
            /** Warnings */
            warnings: string[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    csrf_api_v1_auth_csrf_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CSRFResponse"];
                };
            };
        };
    };
    register_api_v1_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthProfile"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthProfile"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthProfile"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_members_api_v1_members_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    set_availability_api_v1_members__membership_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                membership_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Availability"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_evidence_api_v1_runs__run_id__evidence__evidence_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
                evidence_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_evidence_api_v1_previews__preview_id__evidence__evidence_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                preview_id: string;
                evidence_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_conversation_api_v1_agent_conversations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConversationCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationSnapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    snapshot_api_v1_agent_conversations__conversation_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationSnapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    message_api_v1_agent_conversations__conversation_id__messages_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MessageRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_api_v1_agent_conversations__conversation_id__confirm_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfirmRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_api_v1_agent_conversations__conversation_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CancelRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    recover_create_api_v1_agent_conversations__conversation_id__create_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateMonitorResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    events_api_v1_agent_conversations__conversation_id__events_get: {
        parameters: {
            query?: {
                after?: string | null;
            };
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description SSE id is the conversation sequence; data is an EventEnvelope. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": {
                        /**
                         * Schema Version
                         * @default 1
                         * @constant
                         */
                        schema_version: 1;
                        /**
                         * Event Id
                         * Format: uuid
                         */
                        event_id: string;
                        /** Seq */
                        seq: number;
                        /**
                         * Conversation Id
                         * Format: uuid
                         */
                        conversation_id: string;
                        /**
                         * Agent Run Id
                         * Format: uuid
                         */
                        agent_run_id: string;
                        /**
                         * Type
                         * @enum {string}
                         */
                        type: "message.delta" | "message.completed" | "tool.started" | "tool.completed" | "tool.failed" | "approval.required" | "run.completed" | "run.failed" | "run.cancelled";
                        /** Payload */
                        payload: {
                            [key: string]: unknown;
                        };
                        /** Tool Call Id */
                        tool_call_id?: string | null;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_groups_api_v1_notification_groups_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_Group_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_group_api_v1_notification_groups_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NotificationGroupSpec"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Group"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_group_api_v1_notification_groups__group_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                group_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Group"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    replace_group_api_v1_notification_groups__group_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                group_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NotificationGroupSpec"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Group"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_group_api_v1_notification_groups__group_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                group_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Group"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_group_api_v1_notification_groups__group_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                group_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GroupPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Group"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_templates_api_v1_email_templates_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_Template_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_template_api_v1_email_templates__template_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                template_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Template"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_template_api_v1_email_templates__template_id__preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                template_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NotificationPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RenderedEmail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_deliveries_api_v1_email_deliveries_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_Delivery_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_delivery_api_v1_email_deliveries__delivery_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                delivery_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Delivery"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_routes_api_v1_monitors__monitor_id__notification_routes_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                monitor_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RouteView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    request_route_preview_api_v1_monitors__monitor_id__notification_routes_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                monitor_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoutePreviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoutePreviewJob"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    route_preview_status_api_v1_monitors__monitor_id__notification_routes_preview__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                monitor_id: string;
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreviewJobStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    finish_route_preview_api_v1_monitors__monitor_id__notification_routes_preview__job_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                monitor_id: string;
                job_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoutePreviewFinish"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoutePreview"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_route_preview_api_v1_monitors__monitor_id__notification_routes_confirm_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                monitor_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RouteConfirmRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RouteUpdate"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_monitors_api_v1_monitors_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_MonitorView_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_monitor_api_v1_monitors__monitor_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                monitor_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonitorDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_monitor_runs_api_v1_monitors__monitor_id__runs_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path: {
                monitor_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_RunView_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_manual_run_api_v1_monitors__monitor_id__runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                monitor_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["webmonitor__schemas__monitor_api__RunView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_run_api_v1_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pause_monitor_api_v1_monitors__monitor_id__pause_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                monitor_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonitorView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resume_monitor_api_v1_monitors__monitor_id__resume_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                monitor_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonitorView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_run_api_v1_runs__run_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["webmonitor__schemas__monitor_api__RunView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_events_api_v1_events_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_EventView_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    acknowledge_event_api_v1_events__event_id__acknowledge_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                event_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    live_api_v1_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    ready_api_v1_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
